### ISSUE TITLE
How to get uniform values?

### ISSUE THREAD

**Issue by feuerbach** [emil-e/rapidcheck#140]
I probably misunderstand how I am supposed to use custom generators or `inRange`, but here's what I tried:

``` cpp
#include <rapidcheck.h>
#include <vector>

using namespace std;

inline vector<char> aString() {
  return *rc::gen::container<std::vector<char>>(rc::gen::inRange('a', 'e'));
}

int main() {
  rc::check("test",
            []() {
              const vector<char> s = aString();
              if (!s.empty())
                RC_TAG(s[0]);
            });

  return 0;
}
```

I get a highly skewed distribution:

```
OK, passed 100 tests
52.00% - 97
25.00% - 98
14.00% - 99
 4.00% - 100
```

**Comment by emil-e** [comment]
This is because of sizing. Test case size increases from `0` to `100`. For small sizes, `inRange` does not use the full range of values, only the lower ones in order to make it more likely to get duplicates, something which is requires to produce some categories of bugs.

If this is not desired, I'd suggest using `gen::element(std::string("abcd"))` or `gen::resize(kNominalSize, gen::inRange('a', 'e'))`.

**Comment by feuerbach** [comment]
Great, thank you.
