### ISSUE TITLE
Option to disable exception propagation usage to allow for cross compiling for arm

### ISSUE THREAD

**Issue by WojciechMigda** [emil-e/rapidcheck#147]
Currently, rapidcheck makes use of `std::current_exception` and `std::rethrow_exception` api. Unfortunately, arm gcc cross compiler toolchain doesn't support exception propagation and such compilation fails.
Inclusion of headers which define `std::current_exception` and `std::rethrow_exception` is guarded by `(ATOMIC_INT_LOCK_FREE > 1)` in `<exception>` c++ header.
It would be nice if exception propagation could be disabled in compile time.
Arm cross compiler tested:
```
$ arm-linux-gnueabi-g++ --version
arm-linux-gnueabi-g++ (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by WojciechMigda** [comment]
Problem is hardware-dependent. Rapidcheck compiles if I use `-march=armv7-a` flag.
More background here: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58938

**Comment by emil-e** [comment]
It's likely possible to implement some sort of replacement (i.e. don't propagate the exception, throw some other exception instead) for this behavior that doens't rely on exception pointers and related functions but since this is a bug in GCC, I'm not to keen on implementing such a workaround. Exception pointers are required by the standard and they are not fringe feature so thus I would say that compiler that do not support this are supported.
