### ISSUE TITLE
How can I construct an Arbitrary instance for (unions of) C-style arrays?

### ISSUE THREAD

**Issue by milesgould** [emil-e/rapidcheck#162]
I'm trying to construct an arbitrary 16-byte array of unsigned chars, representing an IPv6 address. Well, actually I'm trying to generate a Microsoft `in6_addr`  structure, defined as

```
typedef struct in6_addr {
    union {
        UCHAR       Byte[16];
        USHORT      Word[8];
    } u;
} IN6_ADDR, *PIN6_ADDR, FAR *LPIN6_ADDR;
```

... but I'm falling at the first hurdle. I can ask for a `std::array<Byte, 16>` and apply `reinterpret_cast` in my test code, but I'd like to construct an Arbitrary instance for the type so I can use it to build Arbitrary instances for bigger objects. Is this possible?

**Comment by emil-e** [comment]
There is no support for this since the entirety of RapidCheck relies on having destructors automatically clean up resources for generated values.

Personally, I would do what you're doing, generate a `vector` or `array` and convert that. You could create an Arbitrary instance for `std::unique_ptr<in6_addr>` so that when RapidCheck handles the object internally it is indeed automatically destroyed. When you want to use it yourself, you'd need to steal the pointer and then it's your own responsibility to clean it up.

**Comment by milesgould** [comment]
OK, thanks!

**Comment by milesgould** [comment]
Possibly stupid question: if I construct examples piece-by-piece in the middle of my test cases like this, will they shrink properly? I'd been assuming that you'd need to pass any examples in as parameters to the test so they get picked up as needing shrinking, and construct each example using a single big `Gen` instance so the shrinks are correlated, but I see that [some of your examples are written in this style](https://github.com/emil-e/rapidcheck/blob/master/examples/gtest/main.cpp#L19), so I guess it must work?

I know Hypothesis supports this by [generating all examples from a shared bytestream and shrinking that](http://www.drmaciver.com/2015/09/a-new-approach-to-property-based-testing/), but I understand that it's a problem for most property-based testing libraries.

**Comment by emil-e** [comment]
It is not at all a stupid question and it is actually the whole reason why I would advice not using `operator*` when there is another convenient option.

When using `operator*`, you can have one generator depend on a previously generated value. This means that when using `operator*`, if we pick two values two values one after another, we cannot go back and shrink the first value once we have started shrinking the second. This is because shrinking the first value would make the second value invalidated. Values picked with `operator*` might still be independent but RapidCheck cannot be sure of this.

When using parameters or other "smarter" combinators (i.e. `gen::container`), RapidCheck can be certain values are independent and thus can keep shrinking them all alternately until all options are exhausted.

**Comment by milesgould** [comment]
That makes sense - thanks!
