### ISSUE TITLE
How to write a generator for an enum?

### ISSUE THREAD

**Issue by louwers** [emil-e/rapidcheck#256]
Say we have a simple enum:

```cpp
enum Action {
    LEFT,
    STRAIGHT,
    RIGHT
};
```

How would one write a generator for it?

I would like to lists of random `Action`s.

**Comment by louwers** [comment]
Answering my own question:

```cpp
std::vector<Action> ALL_ACTIONS({Action::LEFT, Action::STRAIGHT, Action::RIGHT});

namespace rc {

template<>
struct Arbitrary<Action> {
  static Gen<Action> arbitrary() {
    return gen::elementOf(ALL_ACTIONS);
  }
};

} // namespace rc
```

**Comment by Thorius** [comment]
EDIT: Just about to post but I saw you answered it yourself. Posting just in case someone is searching for a generic solution.

I would suggest using `gen::elementOf` or `gen::elements` as that is the simplest way especially if you need it just for one enum.

If you need something more generic you can use something like the type traits from [magic_enum](https://github.com/Neargye/magic_enum) to write a generic version (but this only makes sense if you have a bunch of enums and is probably an overkill to be honest). An alternative middle ground solution would be to follow some conventions for defining enums so that you can extract the max number of elements (a la `MAX_SIZE` enum value at the end) and use a generator for underlying types of the enum.

**Comment by louwers** [comment]
@Thorius Thanks @Thorius. magic_enum looks very useful.
