### ISSUE TITLE
Infinite loop when using rc::gen::container<std::set> with rc::gen::inRange

### ISSUE THREAD

**Issue by pereckerdal** [emil-e/rapidcheck#40]
As of 59f5f4e024ebac38ec65fd69bbc21682113bbc45, this code does not terminate:

    rc::check("", [] {
      *rc::gen::container<std::set<int>>(rc::gen::inRange(0, 1));
    });

The same thing happens when generating an `std::unordered_set`, It works when using `rc::gen::arbitrary<int>()` and it works when generating an `std::vector<int>`.

**Comment by emil-e** [comment]
Will take a look.

**Comment by pereckerdal** [comment]
Cool! It's not very hard for me to work around it, but it did surprise me

**Comment by emil-e** [comment]
Now I see... this is a known issue. The problem is that the size of the set is a random number in the range `[0, size + 1)`. When you use `gen::inRange(0, 1)`, there is only one possible value so you can never generate a set larger than 1 element. So RapidCheck will repeatedly pick values from the element generator until it get enough unique values, which in this case will never happen.

There are a few ways to solve it but some that comes to mind is:
- Fail generation after `N` tries. This will cause the test case to be discarded and if this happens repeatedly, RapidCheck will give up on the entire property. This the most semantically clear solution in that the size of a generated set is distributed in a predictable way.
- Instead of failing the generation, return what we have. This is very do-what-I-mean but I fear that it's not necessarily what people mean and might hide actual bugs because of unintuitive input distribution.

Would love to hear your thoughts on this, I've though a bit too much about this ;)

**Comment by pereckerdal** [comment]
Aha! That makes sense. I think the first option of failing hard makes sense. I would have understood what was going on then. What I'm trying to do is to generate a random object graph for my marking (as in mark&sweep, mark&compact) algorithm(s) to visit.

Here's the code I've ended up with:

```cpp
template<typename Container>
void removeDuplicates(Container &container) {
  std::sort(container.begin(), container.end());
  const auto it = std::unique(container.begin(), container.end());
  container.resize(std::distance(container.begin(), it));
}

struct ObjectGraph {
  using Ref = int;
  using Refs = std::vector<Ref>;
  using Objects = std::unordered_map<Ref, Refs>;
  int num_objects;
  Objects objects;
};

namespace rc {

template<>
struct Arbitrary<ObjectGraph> {
  static Gen<ObjectGraph> arbitrary() {
    return gen::exec([] {
      ObjectGraph graph;
      graph.num_objects = *rc::gen::inRange(1, 100);

      const auto ref_generator = rc::gen::inRange(0, graph.num_objects);
      graph.objects = *rc::gen::container<ObjectGraph::Objects>(
          ref_generator, rc::gen::container<ObjectGraph::Refs>(ref_generator));

      for (auto &object : graph.objects) {
        removeDuplicates(object.second);
      }

      return graph;
    });
  }
};

}  // namespace rc
```

I don't know if this is a sane way to do it, I'm pretty new to this stuff :smile:

**Comment by pereckerdal** [comment]
ehh. The code I posted doesn't work for the same reason I filed this bug. Well well.

Would it be possible to make some kind of optional meta generator that can be used for `set` and `unordered_set` that provides behavior #2 that you suggested? That would be nice

**Comment by emil-e** [comment]
Instead of removing duplicates, you could maybe use `gen::unique` or `gen::uniqueBy`.

Regarding behavior no 2, It could be a flag, to `gen::container` maybe? Like `gen::container<...>(myGen, rc::gen::bestEffort)` or something?

**Comment by emil-e** [comment]
Another option for you would be to ensure that there are enough elements that can be generated using gen::withSize to pass the the size or the size multiplied by a factor to gen::inRange.

**Comment by pereckerdal** [comment]
In my case, I know in advance how many distinct objects that can be created (it's `num_objects`). So I managed to emulate the `rc::gen::bestEffort` flag using

```cpp
const auto ids_generator = rc::gen::resize(
    num_objects, rc::gen::container<std::set<ObjectGraph::Id>>(id_generator));
```

I set `num_objects` to

```cpp
*rc::gen::withSize([](int size) {
  return rc::gen::inRange(0, size);
})
```

With that, I think I have what I need. `unique` was pretty handy, thanks for the pointer to that.

I think the main thing that would help here is to fail instead of looping forever. The rest I could figure out. While the `bestEffort` flag would be neat (that name is a bit confusing though), I was able to do all that I needed with `resize`.

Thanks for the help! :smile:

**Comment by pereckerdal** [comment]
(feel free to reopen if you want to use this to track follow-up tasks from this)

**Comment by emil-e** [comment]
Will use this to track the adding of failure to container generation.

**Comment by emil-e** [comment]
@pereckerdal
I actually mislead you about `gen::inRange` by the way, using that with size is probably not what you want since the default behavior is actually to scale the used range with size. The whole range is only used at `rc::kNominalSize`. If you always want to use the maximum size, `gen::resize(kNominalSize, gen::inRange(0, 100))` is what you want.

Also, regarding containers, there is a fixed length version of `gen::container` that takes the length as an argument. However, that does not shrink in length, it only shrinks the elements, for obvious reasons.
