### ISSUE TITLE
Double fixture initialization with RC_GTEST_FIXTURE_PROP

### ISSUE THREAD

**Issue by frejk** [emil-e/rapidcheck#78]
Excellent work!

Trying RapidCheck out, I have one issue though. Using the gtest integration causes fixture to be initialized twice.

The following test case shows the problem:
```C++

struct TestFixture : public ::testing::Test {
   static int initCounter;

   TestFixture() {
      std::cout << "Creating fixture" << std::endl;
      initCounter ++;
   }

   ~TestFixture() {
      std::cout << "Destructing fixture" << std::endl;
      initCounter --;
   }
};

int TestFixture::initCounter = 0;

RC_GTEST_FIXTURE_PROP( TestFixture, TestInitCount, () ){
   std::cout << "RC_GTEST_FIXTURE_PROP(), initCounter: " << initCounter << std::endl;
}

TEST_F(TestFixture, ThisIsATest) {
   std::cout << "TEST_F(), initCounter: " << initCounter  << std::endl;
}
```

The output becomes:
```
Note: Google Test filter = TestFixture.*
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from TestFixture
[ RUN      ] TestFixture.TestInitCount
Creating fixture
Creating fixture
RC_GTEST_FIXTURE_PROP(), initCounter: 2
Destructing fixture
Creating fixture
RC_GTEST_FIXTURE_PROP(), initCounter: 2
Destructing fixture
Creating fixture
RC_GTEST_FIXTURE_PROP(), initCounter: 2
Destructing fixture
Destructing fixture
[       OK ] TestFixture.TestInitCount (1 ms)
[ RUN      ] TestFixture.ThisIsATest
Creating fixture
TEST_F(), initCounter: 1
Destructing fixture
[       OK ] TestFixture.ThisIsATest (0 ms)
[----------] 2 tests from TestFixture (1 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (1 ms total)
[  PASSED  ] 2 tests.
```

In my case, this causes problems with code that has static members that can't be initialized twice.

**Comment by emil-e** [comment]
Yeah, this is definitely looks like a bug. The problem seems to be that a fixture is instantiated for the whole property, not just for each test case. If you look at https://github.com/emil-e/rapidcheck/blob/master/extras/gtest/include/rapidcheck/gtest.h#L51, you can see that the `TEST_F` is used. It should use the `TEST` macro instead. You can try it and send a PR if you want, otherwise I will fix it as soon as I get the time for it.

However, I advice strongly against having static data members in fixtures. When parallel execution support is added, you will not be able to take advantage of it if you do.

**Comment by frejk** [comment]
That was quick.

Two comments on your fix. 
First, it is a pitty that is no longer possible to mix `RC_GTEST_FIXTURE_PROP` and `TEST_F` since `RC_GTEST_FIXTURE_PROP` is now a `TEST` and gtest does not allow mixing these, but the issue is solved. Perhaps one doesn't need the mixing.
Second, as you mention in your comment, filtering on `Fixture` no longer finds the test case, since it is renamed to `Fixture_RapidCheck>`. Renaming isn't really necessary. `TEST(Fixture, Name)` in gtest.h#L51 works fine, and filtering still finds the test case. What do you think of undoing the renaming?

Yes, I agree regarding static members in fixtures. My problem is in legacy code that i try RapidCheck out on, and is instantiated in the fixture. The legacy code has static members.

**Comment by emil-e** [comment]
RapidCheck needs to instantiate the fixture for each case that is run and thus cannot use the built-in TEST_F macro. The fact that it was ever used was a bug, it was never intended, that's what caused the double instantiation. It instead uses TEST to register the test with Google Test but does the fixture instantiation on its own. However, Gtest does not allow mixing of TEST_F and TEST for the same test case so the only way to mix TEST_F and RC_GTEST_FIXTURE_PROP is to register the RapidCheck property under a different test case name so that it doesn't clash with the TEST_F usage of your regular Google Test fixture tests.

The point is that you CAN use RC_GTEST_FIXTURE_PROP and TEST_F intermixed for the same fixture class since they are registered under different test case names. They use the same fixture but different test car names. It's unfortunate that they are not under the same test case but I couldn't come up with a better solution because of these limitations in Gtest.

**Comment by frejk** [comment]
Ah, ok. Well, as long as you're aware of the renaming it's no problem. Something to add to an FAQ perhaps.

**Comment by emil-e** [comment]
If you have another solution which allows you to mix RapidCheck properties and Google tests for the same fixture I'm definitely open to trying it.
