### ISSUE TITLE
Exhaustive testing

### ISSUE THREAD

**Issue by simon-bourne** [emil-e/rapidcheck#94]
Hi, it would be great to be able to exhaustively check a function like with smallcheck.

**Comment by emil-e** [comment]
I'm not sure that adding this functionality to RapidCheck would necessary make sense even though it's also a very useful form of testing. It might make more sense as a separate framework.

It could possibly be added by adding a method to rc::Gen that instead of a Shrinkable returns a Seq of successively larger values.

**Comment by simon-bourne** [comment]
I see your point about it possibly being a different framework. There wouldn't be much overlap, and I guess you could write an adaptor to translate finite state deterministic generators into random ones.

**Comment by matthijskooijman** [comment]
I'm also wondering about exhaustive testing for rapidcheck. I just wrote my first test for rapidcheck, which has only one free variable that selects from a list of 8 or so predefined types. It seems that rapidcheck is randomly trying values, repeating the same value a bunch of times. I guess rapidcheck is intended for bigger test spaces, but would be interesting if it could also work efficiently on smaller test spaces, avoiding duplicates and perhaps also be instructed to do an exhaustive test.

AFAICS rapidcheck already has access to most of the information (except maybe when using custom generators) needed to implement something like this.
